// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:meshtastic/model/project/data.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ProjectDataAdapter());
    registerAdapter(SheetItemDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ProjectDataAdapter());
    registerAdapter(SheetItemDataAdapter());
  }
}
